export const CREATE_CONTACT_REQUEST ='CREATE_CONTACT_REQUEST'
export const CREATE_CONTACT_SUCCESS ='CREATE_CONTACT_SUCCESS'
export const CREATE_CONTACT_FAILED ='CREATE_CONTACT_FAILED'

export const READ_CONTACT_REQUEST='READ_CONTACT_REQUEST'
export const READ_CONTACT_SUCCESS='READ_CONTACT_SUCCESS'
export const READ_CONTACT_FAILED='READ_CONTACT_FAILED'
